Add failing test case
Version info:

    $ python3 --version
    Python 3.4.2

    $ pip3 show GitPython
    ---
    Name: GitPython
    Version: 2.0.8
    Location: /rw/usrlocal/lib/python3.4/dist-packages
    Requires: gitdb

    $ lsb_release -a
    No LSB modules are available.
    Distributor ID: Debian
    Description:    Debian GNU/Linux 8.6 (jessie)
    Release:    8.6
    Codename:   jessie

And the failure itself:

    $ ./test.py
    Traceback (most recent call last):
      File "./test.py", line 9, in <module>
        tuple(tree)
      File "/usr/local/lib/python3.4/dist-packages/git/objects/tree.py", line 207, in _iter_convert_to_object
        path = join_path(self.path, name)
      File "/usr/local/lib/python3.4/dist-packages/git/util.py", line 100, in join_path
        if b.startswith('/'):
    TypeError: startswith first arg must be bytes or a tuple of bytes, not str